### ISSUE TITLE
Accounts dropdown menu

### ISSUE THREAD

**Issue by janat08** [railstutorial/sample_app_rails_4#43]
Upon loading the repository into local server, there's error display on local port about application.html line 7, the part where it tags application for javascript, reverting it to default is passable but accounts dropdown menu stops working. There is already a stopic specifically for the issue, that explains how to solve the issue, but for the daft- me- could you solve it.

**Comment by janat08** [comment]
Also for people lacking in patience maybe include loads of comments about what does what as to enable them to learn by example rather than imagine and conceptualize things as they read the book, because I imagine that's the point here.

**Comment by mhartl** [comment]
Thanks for your comments. This repo is the sample app for the Rails 4.0 version and is no longer actively maintained. Please use the [reference app for the 3rd edition](https://github.com/mhartl/sample_app_3rd_edition) instead.
