### ISSUE TITLE
Chapter 12 - syntax no longer valid

### ISSUE THREAD

**Issue by Mirv** [railstutorial/sample_app_rails_4#57]
Chapter 12 - [12.3.3](https://www.railstutorial.org/book/password_reset#sec-password_reset_test) - Figure 12.18

In "test/integration/password_resets_test.rb", the params syntax in here throws errors unless removed, per stackoverflow - [Link](http://stackoverflow.com/questions/40268250/ruby-on-rails-tutorial-integration-test-valid-invalid-user-info-sign-failing):

```
... # Valid email
    post password_resets_path,
         params: { ...
```

Working example of that issue resolved (I have one more lingering issue in this github example)... [Link](https://github.com/Mirv/railstut-01/blob/master/test/integration/password_resets_test.rb)

**Comment by mhartl** [comment]
This syntax is valid as long as you use the gem versions used in this version of the tutorial. For the most up-to-date version, see [railstutorial.org](http://railstutorial.org/).
