### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by ssriera** [railstutorial/sample_app_rails_4#58]
The link for `Hack railstutorial/sample_app_rails_4 on Nitrous.IO` is broken.

**Comment by mhartl** [comment]
Thanks for the note. This repo is no longer maintained. See [here](https://bitbucket.org/railstutorial/sample_app_4th_ed) for the most up-to-date version.

**Comment by ssriera** [comment]
Oh, wasn't aware. Thanks! 😸

**Comment by mhartl** [comment]
No worries. I appreciate the heads-up in any case! 🙂
