### ISSUE TITLE
Heroku problem

### ISSUE THREAD

**Issue by stealwin** [railstutorial/sample_app_rails_4#62]
When i try deploying no herouku sample_app , i get the error message:
` Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. `
I use Ruby 2.4.2 and Rails 5.1.4.

**Comment by mhartl** [comment]
Thanks for the report. Unfortunately, I don't have the resources to offer individual technical support on the Rails Tutorial. I suggest consulting the resources on the [Rails Tutorial Help page](http://railstutorial.org/help) to resolve the issue. (The likeliest source of problems is accidentally leaving the `sqlite3` gem in the production Heroku environment.) 
![screen shot 2017-12-08 at 10 33 41 am](https://user-images.githubusercontent.com/6232/33779812-47452030-dc03-11e7-977f-cf8686144d3d.png)

**Comment by stealwin** [comment]
Thanks for your answer, but it's still not working, in heroku logs i read 
`Gem::LoadError: can't activate pg (~> 0.18), already activated pg-0.15.1. Make sure all dependencies are added to Gemfile`
`Gem::LoadError: Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
`
But in gemfile i wrote  
gem 'pg', ' ~> 0.18'
  gem 'rails_12factor', '0.0.

**Comment by mhartl** [comment]
I run into issues like this all the time. Unfortunately, there's no substitute for Googling and persistence.

**Comment by stealwin** [comment]
Is it Heroku is  one of fundamental thing in this book, or i can solve that problem at the end of book?

**Comment by mhartl** [comment]
You can skip it for now, though it's recommended to deploy frequently. I suggest deleting everything and starting over to see if you can get it to work. The tutorial has been extensively debugged, so it's likely that you just missed a small step at some point.

**Comment by stealwin** [comment]
Thanks, i try it step!
